import { readFile, writeFile, mkdir, cp, rm } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'dist');
await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
const assets = ['index.html', 'styles.css', 'core.js', 'app.js', 'sw.js', 'manifest.webmanifest', 'icons', 'LICENSE'];
for (const file of assets) await cp(path.join(root, file), path.join(dist, file), { recursive: true });
await writeFile(path.join(dist, '.nojekyll'), '');
let html = await readFile(path.join(root, 'index.html'), 'utf8');
const license = await readFile(path.join(root, 'LICENSE'), 'utf8');
html = html.replace('<!doctype html>', '<!doctype html>\n<!--\n' + license + '\n-->');
const css = await readFile(path.join(root, 'styles.css'), 'utf8');
const core = await readFile(path.join(root, 'core.js'), 'utf8');
const app = await readFile(path.join(root, 'app.js'), 'utf8');
const svg = await readFile(path.join(root, 'icons/icon.svg'), 'utf8');
html = html.replace(/<link rel="apple-touch-icon"[^>]+>/, '').replace(/<link rel="manifest"[^>]+>/, '');
html = html.replace(/<link rel="icon"[^>]+>/, `<link rel="icon" href="data:image/svg+xml,${encodeURIComponent(svg)}">`);
html = html.replace('<link rel="stylesheet" href="styles.css">', `<style>${css}</style>`);
html = html.replace('  <script src="core.js" defer></script>\n  <script src="app.js" defer></script>', '');
const escapeScript = s => s.replace(/<\/script/gi, '<\\/script');
html = html.replace('</body>', `<script>window.AZ_STANDALONE=true;\n${escapeScript(core)}\n${escapeScript(app)}\n</script>\n</body>`);
await writeFile(path.join(root, 'Absolute-Zero-standalone.html'), html);
console.log(`Built dist/ (${assets.length} asset groups) and Absolute-Zero-standalone.html (${Buffer.byteLength(html)} bytes).`);
